version: 0.0

Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:ap-south-1:981265949290:task-definition/swiggy-task:19
        LoadBalancerInfo:
          ContainerName: "swiggy-app"
          ContainerPort: 80