version: 0.2

env:
  parameter-store:
    SONAR_TOKEN: "/cicd/sonar/sonar-token"
    SONAR_HOST_URL: "/cicd/sonar/sonar-host-url"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Update and install dependencies
      - apt-get update -y
      - apt-get install -y wget unzip curl

      # Install Trivy
      -  curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      # Install Sonar Scanner
      - wget https://github.com/SonarSource/sonar-scanner-cli/releases/download/5.0.1.3006/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip -d /opt/
      - ln -s /opt/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner /usr/local/bin/sonar-scanner
      - sonar-scanner --version

  pre_build:
    commands:
      - echo Logging into ECR
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - AWS_REGION=ap-south-1
      - ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/swiggy-clone
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 7)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "ECR login successful"

  build:
    commands:
      - echo Build started on `date`

      # Trivy filesystem scan
      - echo "Running Trivy filesystem scan..."
      - trivy fs . --format table -o trivyfilescan.txt
      - cat trivyfilescan.txt

      # SonarQube analysis
      - echo "Running SonarQube analysis..."
      - sonar-scanner \
          -Dsonar.projectKey=swiggy-clone \
          -Dsonar.sources=. \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN

      # Docker build
      - echo "Building Docker image..."
      - docker build -t swiggy-clone:$IMAGE_TAG .

      # Trivy image scan
      - echo "Running Trivy image scan..."
      - trivy image swiggy-clone:$IMAGE_TAG --format table -o trivyimagescan.txt
      - cat trivyimagescan.txt

      # Tag image for ECR
      - docker tag swiggy-clone:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
      - docker tag swiggy-clone:$IMAGE_TAG $ECR_URI:latest

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest

      - echo "Writing imagedefinitions.json..."
      - printf '[{"name":"swiggy","imageUri":"%s"}]' $ECR_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - appspec.yaml
    - imagedefinitions.json
    - trivyfilescan.txt
    - trivyimagescan.txt